# Generated by Django 5.1.5 on 2025-01-28 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='candidate_sheet_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='vacancy_sheet_url',
            field=models.URLField(null=True),
        ),
    ]
