# Generated by Django 5.1.5 on 2025-02-12 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='candidate_sheet_url',
            new_name='sheet_url',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='vacancy_sheet_url',
        ),
    ]
