# Generated by Django 5.1.5 on 2025-02-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0002_rename_candidate_sheet_url_organization_sheet_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
