# Generated by Django 5.1.5 on 2025-01-24 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0003_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheets.organization', to_field='org_code'),
        ),
    ]
