# Generated by Django 5.1.5 on 2025-02-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0004_vacancycategory_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancycategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
