# Generated by Django 5.1.5 on 2025-02-13 10:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0005_alter_vacancycategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancycategory',
            name='description',
            field=ckeditor.fields.RichTextField(default='нет описания'),
        ),
    ]
